import Head from "next/head";
import AddTodo from "../components/addTodo";
import TodoList from "../components/todoList";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <>
            <Head>
                <title>Simple Todo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className="fs-1 fw-bold" style={{ margin: "2rem" }}>
                    Super Simple Todo
                </h1>
                <div className="d-flex flex-column" style={{ width: "400px" }}>
                    <AddTodo />
                    <TodoList />
                </div>
            </main>
        </>
    );
}
